from langchain_core.tools import tool

@tool
def owner_earnings(
    net_income: float,
    depreciation_amortization: float = 0.0,
    capital_expenditures: float = 0.0
):
    """
    Calculates the owner earnings of a company.

    Owner earnings represent the cash generated by the business that is 
    available to shareholders after necessary reinvestments.

    Parameters:
        net_income (float): The company's net income.
        depreciation_amortization (float, optional): Non-cash expenses added back to net income. Defaults to 0.0.
        capital_expenditures (float, optional): Cash spent on maintaining or acquiring fixed assets. Defaults to 0.0.

    Returns:
        float: The calculated owner earnings.
    """
    # Owner earnings = Net Income + Non-cash charges - Capital Expenditures
    return net_income + depreciation_amortization - capital_expenditures
